<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Practica_05_Torres_Hanoi</AssemblyName>
    <RootNamespace>Practica_05_Torres_Hanoi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Roboto-Regular.ttf" />
    <EmbeddedResource Include="Resources\MaterialSymbols-Practicas.ttf" />
  </ItemGroup>

</Project>
