<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Practica_03_MCD</AssemblyName>
    <RootNamespace>Practica_03_MCD</RootNamespace>
  </PropertyGroup>

</Project>
